### ISSUE TITLE
Error introduced in awg_context

### ISSUE THREAD

**Issue by leghtas** [Ecpy/ecpy_hqc_legacy#17]
I couldn't transfer sequences to awg. I needed to modify awg_context.py line 174 to become `to_send[int(channel[-1])] = bytearray(aux)`
instead of 
`to_send[int(channel[-1])] = aux.tobytes()`
This way it works.
I see this was introduced in commit "pulses: improve conversion to bytes in AWGContext"

**Comment by MatthieuDartiailh** [comment]
Shit this is a python 2/3 issue or a numpy version issue. I will have to look into it. What was the error, you got ?

**Comment by leghtas** [comment]
It was something like "could not convert to integer", I can run it tomorrow and tell you exactly.

**Comment by leghtas** [comment]
here it is:
```
Logger parametrised
Process running
Task built
Check successful
ERROR: The following unhandled exception occured :
Traceback (most recent call last):
File "d:\users\checkhov\documents\github\ecpy\ecpy\ecpy\tasks\tasks\base_tasks.py", line 1131, in perform
child.perform_()
File "d:\users\checkhov\documents\github\ecpy\ecpy\ecpy\tasks\tasks\decorators.py", line 88, in decorator
return function_to_decorate(*args, **kwargs)
File "d:\users\checkhov\documents\github\ecpy\ecpy_pulses\ecpy_pulses\tasks\tasks\instrs\transfer_sequence_task.py", line 94, in perform
self.driver)
File "d:\users\checkhov\documents\github\ecpy\ecpy_hqc_legacy\ecpy_hqc_legacy\pulses\contexts\awg_context.py", line 191, in compile_and_transfer_sequence
return self._transfer_sequences(driver, to_send, infos)
File "d:\users\checkhov\documents\github\ecpy\ecpy_hqc_legacy\ecpy_hqc_legacy\pulses\contexts\awg_context.py", line 221, in _transfer_sequences
sequences[ch_id])
File "d:\users\checkhov\documents\github\ecpy\ecpy_hqc_legacy\ecpy_hqc_legacy\instruments\drivers\driver_tools.py", line 128, in wrapper
return method(self, *args, **kwargs)
File "d:\users\checkhov\documents\github\ecpy\ecpy_hqc_legacy\ecpy_hqc_legacy\instruments\drivers\visa\tektro_awg.py", line 453, in to_send
self._driver.write_binary_values(header, waveform, datatype='B')
File "C:\Program Files (x86)\Anaconda2\lib\site-packages\pyvisa\resources\messagebased.py", line 268, in write_binary_values
block = util.to_ieee_block(values, datatype, is_big_endian)
File "C:\Program Files (x86)\Anaconda2\lib\site-packages\pyvisa\util.py", line 383, in to_ieee_block
return str(header) + struct.pack(fullfmt, *iterable)
error: cannot convert argument to integer
Process shuting down
```

**Comment by MatthieuDartiailh** [comment]
@leghtas I forgot where we stand for this ? I f we have a fix it may be worth doing a pull request with just this and merging ASAP.

**Comment by leghtas** [comment]
I just pushed a branch and asking for a pull request
