### ISSUE TITLE
Error in handling settings for the magnetic source CS4

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy_hqc_legacy#18]
Unfinished business in Ecpy/ecpy_hqc_legacy#6

When enqueueing (?) a measure containing an apply_magnetic_field task, error message : 

'''
Traceback (most recent call last):
  File "d:\users\hqc\documents\ecpy_hqc_legacy\ecpy_hqc_legacy\instruments\drivers\visa\cryomagnetics_cs4.py", line 39, in __init__
    mc = connection_info['magnet_conversion']
KeyError: 'magnet_conversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\hqc\documents\ecpy_hqc_legacy\ecpy_hqc_legacy\instruments\starters\legacy_starter.py", line 39, in check_infos
    driver = driver_cls(c)
  File "d:\users\hqc\documents\ecpy_hqc_legacy\ecpy_hqc_legacy\instruments\drivers\visa\cryomagnetics_cs4.py", line 45, in __init__
    the switch heater current is correct.'''))
ecpy_hqc_legacy.instruments.drivers.driver_tools.InstrIOError: The field to current ratio
of the currently used magnet need to be specified in
the instrument settings. One should also check that
the switch heater current is correct.
'''

**Comment by MatthieuDartiailh** [comment]
At least we know that the error message is helpful.
