### ISSUE TITLE
Can't browse through existing instruments profile

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy_hqc_legacy#5]
![erreur_image](https://cloud.githubusercontent.com/assets/11089557/20341143/23a1d64a-abe5-11e6-99dc-d823c25e289a.png)

Right now I don't have all libraries correctly installed (see below), is it the source of the problem ? It shouldn't crash all the drivers, should it ?

'''
Failed to import ecpy_hqc_legacy.instruments.drivers.visa.yokogawa :
Traceback (most recent call last):
File "D:\Users\hqc\Anaconda\lib\site-packages\ecpy\utils\declarator.py", line 176, in import_and_get
mod = import_module(path)
File "D:\Users\hqc\Anaconda\lib\importlib\__init__.py", line 37, in import_module
__import__(name)
File "D:\Users\hqc\Anaconda\lib\site-packages\ecpy_hqc_legacy\instruments\drivers\visa\yokogawa.py", line 21, in <module>
from ..visa_tools import VisaInstrument, errors
File "D:\Users\hqc\Anaconda\lib\site-packages\ecpy_hqc_legacy\instruments\drivers\visa_tools.py", line 22, in <module>
raise_with_traceback(ImportError(msg))
File "D:\Users\hqc\Anaconda\lib\site-packages\ecpy_hqc_legacy\instruments\drivers\visa_tools.py", line 18, in <module>
from pyvisa.highlevel import ResourceManager
ImportError: The PyVISA library is necessary to use the visa backend.
'''

**Comment by MatthieuDartiailh** [comment]
Without Visa no driver can be imported so it is indeed expected. I think I added pyvisa to ecpy_hqc_legacy dependencies so in next version it should pick it up. One question : was only the yokogawa poping in the logs ? Actually all drivers should I think.

**Comment by lcontami** [comment]
Yes only the yokogawa
