### ISSUE TITLE
pyqt not found

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy_hqc_legacy#58]
Installing exopy_hqc_legacy and trying to run exopy gives the following error message:

```
Could not load extension package exopy_hqc_legacy : Traceback (most recent call last):
  File "D:\Users\hqc\Anaconda2\envs\exopy_dvp\lib\site-packages\exopy\app\packages\plugin.py", line 61, in collect_and_register
    ep.require()
  File "D:\Users\hqc\Anaconda2\envs\exopy_dvp\lib\site-packages\pkg_resources\__init__.py", line 2363, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "D:\Users\hqc\Anaconda2\envs\exopy_dvp\lib\site-packages\pkg_resources\__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyqt5' distribution was not found and is required by exopy
```

pyqt=5.6.0 is installed.

**Comment by MatthieuDartiailh** [comment]
This should not be present on master. We had to update the setup.py script because anaconda package was not properly recognized by setuptools. Check if your install does not have an old egg file lying around.

**Comment by lcontami** [comment]
I had just created a new environment

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by MatthieuDartiailh** [comment]
What version of Python ? Your Anaconda is running Python 2 I assume from the name so it may have created a Python 2 env.
How did you install exopy (conda, pip from master...) ?

**Comment by lcontami** [comment]
python=3.6.2
exopy (0.2.0.dev.post25) and exopy pulses are installed via conda;
I install exopy_hqc_legacy with conda, then removed it with --force, then installed a local version in develop mode via
python setup.py develop

Side question: I tried updating exopy_hqc_legacy in another env (where it is installed with conda).
Need there be a new release for the code to be updated through conda update or is it supposed to update to the last version of master no matter what ?

**Comment by MatthieuDartiailh** [comment]
Look at your setup.py file. If pyqt is listed under install_requires remove it. It may be that your are working on an old branch.

We build and upload nighty release of every package when the CI test master so you should get the equivalent of master (assuming the build completed).

**Comment by lcontami** [comment]
here is the file:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages

import os.path
import sys

sys.path.insert(0, os.path.abspath('.'))
from exopy_hqc_legacy.version import __version__


def long_description():
    """Read the project description from the README file.

    """
    with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as f:
        return f.read()


setup(
    name='exopy_hqc_legacy',
    description='Transitional package between HQCMeas and Exopy',
    long_description=long_description(),
    version=__version__,
    author='see AUTHORS',
    author_email='m.dartiailh@gmail.com',
    url='https://github.com/exopy/exopy_hqc_legacy',
    download_url='https://github.com/exopy/exopy_hqc_legacy/tarball/master',
    keywords='experiment automation GUI',
    license='BSD',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'License :: OSI Approved :: BSD License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Topic :: Scientific/Engineering :: Physics',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        ],
    zip_safe=False,
    packages=find_packages(exclude=['tests', 'tests.*']),
    package_data={'': ['*.enaml']},
    python_requires='>=3.5',
    setup_requires=['setuptools'],
    install_requires=['exopy', 'pyvisa', 'h5py', 'numpy', 'pyclibrary'],
    entry_points={
        'gui_scripts':
        'hqcmeas_to_exopy = exopy_hqc_legacy.conversion.__main__:main',
        'exopy_package_extension':
        'exopy_hqc_legacy = exopy_hqc_legacy:list_manifests'}
)
```

**Comment by MatthieuDartiailh** [comment]
Sorry I misread an error message. You need to update exopy. post26 contain the fix for your issue.

**Comment by lcontami** [comment]
How ? conda update exopy tells me that it is up to date.
conda install exopy=0.2.0.dev.post26 does not work.
I installed it today so I am confused as to why I don't have the latest version.

```
(exopy_dvp) D:\Users\hqc>conda install exopy=0.2.0.dev.post26 -c exopy
Fetching package metadata .............
Solving package specifications:


PackageNotFoundError: Package not found: '' Package missing in current win-64 ch
annels:
  - exopy 0.2.0.dev.post26*

You can search for packages on anaconda.org with

    anaconda search -t conda exopy
```

**Comment by MatthieuDartiailh** [comment]
That's weird those files do exist at https://anaconda.org/Exopy/exopy/files

**Comment by MatthieuDartiailh** [comment]
Can you post the output of conda list ?

**Comment by lcontami** [comment]
```
(exopy_dvp) D:\Users\hqc>conda list
# packages in environment at D:\Users\hqc\Anaconda2\envs\exopy_dvp:
argh                      0.26.1                   py36_0    exopy
atom                      0.4.1                    py36_0    exopy
blas                      1.0                         mkl
certifi                   2016.2.28                py36_0
configobj                 5.0.6                    py36_0
enaml                     0.10.2.post1             py36_1    exopy
exopy                     0.2.0.dev.post25         py36_25    exopy
exopy_pulses              0.2.0.dev.post14         py36_14    exopy
future                    0.16.0                   py36_1
h5py                      2.7.0               np113py36_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
icu                       57.1                     vc14_0  [vc14]
jpeg                      9b                       vc14_0  [vc14]
kiwisolver                1.0.1.post2              py36_2    exopy
libpng                    1.6.30                   vc14_1  [vc14]
mkl                       2017.0.3                      0
numpy                     1.13.1                   py36_0
openssl                   1.0.2l                   vc14_0  [vc14]
pathtools                 0.1.2                    py36_0    exopy
pip                       9.0.1                    py36_1
ply                       3.10                     py36_0
pyclibrary                0.1.4                     <pip>
pyclibrary                0.1.4.post15             py36_0    exopy
pyqt                      5.6.0                    py36_2
python                    3.6.2                         0
pyvisa                    1.9.0.post0              py36_0    exopy
pyyaml                    3.12                     py36_0
qt                        5.6.2                    vc14_6  [vc14]
qtawesome                 0.4.4                    py36_0
qtpy                      1.3.1                    py36_0
setuptools                36.4.0                   py36_1
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
vc                        14                            0
vs2015_runtime            14.0.25420                    0
watchdog                  0.8.3                    py36_0    exopy
wheel                     0.29.0                   py36_0
wincertstore              0.2                      py36_0
zlib                      1.2.11                   vc14_0  [vc14]

(exopy_dvp) D:\Users\hqc>pip list
DEPRECATION: The default format will switch to columns in the future. You can us
e --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con
f under the [list] section) to disable this warning.
argh (0.26.1)
atom (0.4.1)
certifi (2016.2.28)
configobj (5.0.6)
enaml (0.10.2)
exopy (0.2.0.dev0)
exopy-hqc-legacy (0.2.0.dev0, d:\users\hqc\documents\exopy_hqc_legacy)
exopy-pulses (0.2.0.dev0)
future (0.16.0)
h5py (2.7.0)
kiwisolver (1.0.1)
numpy (1.13.1)
pathtools (0.1.2)
pip (9.0.1)
ply (3.10)
pyclibrary (0.1.4)
PyVISA (1.9.0)
PyYAML (3.12)
QtAwesome (0.4.4)
QtPy (1.3.1)
setuptools (36.4.0)
six (1.10.0)
watchdog (0.8.3)
wheel (0.29.0)
wincertstore (0.2)
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
```

**Comment by MatthieuDartiailh** [comment]
I don't have a clear idea of what is happening here. A quick dirty fix is to go into exopy egg in site packages and remove pyqt from the require file.
